### ISSUE TITLE
Location and Description missed out in calendar events (And solution)

### ISSUE THREAD

**Issue by Cybersmurfen** [tybritten/ical-sensor-homeassistant#103]
Noticed that above attributes are missing out after the latest update. Please test the component properly before releasing a new version.

I'm no contributor but this is easily fixed in calendar.py:

Change:
self._event = CalendarEvent(event["start"], event["end"], event["summary"])
To:
self._event = CalendarEvent(event["start"], event["end"], event["summary"], event["description"], event["location"])

Add this just before the above:

(location, offset) = extract_offset(event["location"], OFFSET)
event["location"] = location
(description, offset) = extract_offset(event["description"], OFFSET)
event["description"] = description

**Comment by PipeChess** [comment]
This should be addressed in the repo. I am running into this problem in an automation where a condition should check for a specific word in the description of the trigger event. Always fails. Description and location are both not on the trigger event.

I'll try your approach next and change it directly in the calendar.py

**Comment by Cybersmurfen** [comment]
I created a pull request.

**Comment by PipeChess** [comment]
Mhhh... I updated the file but after testing out my automation it still doesn't match the condition:

This should now work:
`{{'Microsoft Teams meeting' in trigger.calendar_event.description}}`

**But it still fails with a warning:**
`Template variable warning: 'dict object' has no attribute 'description' when rendering '{{'Microsoft Teams meeting' in trigger.calendar_event.description}}'`

**Comment by Cybersmurfen** [comment]
@PipeChess - I made a pull request but you can replace the whole last function function in calendar.py (Row 71) if you made something wrong: The indents are important and cannot be tabs.

    async def async_update(self):
        """Update event data."""
        _LOGGER.debug("Running ICalCalendarEventDevice async update for %s", self.name)
        await self.ical_events.update()
        event = copy.deepcopy(self.ical_events.event)
        if event is None:
            self._event = event
            return
        (summary, offset) = extract_offset(event["summary"], OFFSET)
        event["summary"] = summary
        (location, offset) = extract_offset(event["location"], OFFSET)
        event["location"] = location
        (description, offset) = extract_offset(event["description"], OFFSET)
        event["description"] = description
        self._offset_reached = is_offset_reached(event["start"], offset)
        self._event = CalendarEvent(event["start"], event["end"], event["summary"], event["description"], event["location"])

**Comment by PipeChess** [comment]
@Cybersmurfen - I did that however same outcome.

```
Here is the autmation I am trying to run with it but the condition always fails:
id: '1661953901563'
alias: Turn On Plug - TEAMS
description: ''
trigger:
  - platform: calendar
    event: start
    offset: '-0:1:0'
    entity_id: calendar.ical_test
condition:
  - condition: template
    value_template: '{{''Microsoft Teams meeting'' in trigger.calendar_event.description}}'
action:
  - type: turn_on
    device_id: b1b2184d62025c98865e75c5750418b0
    entity_id: switch.smart_plug_1_channel
    domain: switch
mode: single
```
**Trace response:**
```
Triggered by the null at September 1, 2022 at 2:59:00 PM
Test template condition
Stopped because a condition failed at September 1, 2022 at 2:59:00 PM (runtime: 0.01 seconds)
```

Here is also the event trigger from the trace, doesn't look like the event gets the properties.


```
trigger:
  id: '0'
  idx: '0'
  platform: calendar
  event: start
  offset:
    __type: <class 'datetime.timedelta'>
    total_seconds: -60
  calendar_event:
    start: '2022-09-01T15:00:00-04:00'
    end: '2022-09-01T15:45:00-04:00'
    summary: Test Meeting
    all_day: false
```
